apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: orchestrator
  project: default
  source:
    repoURL: 'https://airflow.apache.org/'
    targetRevision: 1.8.0
    helm:
      values: |-
        executor: "KubernetesExecutor"
        webserverSecretKeySecretName: my-webserver-secret
        createUserJob:
          useHelmHooks: false
        migrateDatabaseJob:
          useHelmHooks: false
        webserver:
          service: 
            type: LoadBalancer
        data:
          metadataSecretName: airflow-metadata-secret
        postgresql:
          enabled: false
        dags:
          gitSync:
            enabled: true
            repo: "git@github.com:GersonRS/challenge-delta-lake-deep-dive.git"
            branch: main
            rev: HEAD
            depth: 1
            maxFailures: 1
            subPath: "dags"
            sshKeySecret: airflow-ssh-secret
            knownHosts: |-
              |1|yutcXh9HhbK6KCouq3xMQ38B9ns=|V9zQ39gzVxSZ75WU78CGJiVKCOk= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
              |1|7ww9iNXn8d1jtXlaDjt+fYpsRi0=|vfHsTzw+QATWkCKD7kgG2jhu/1w= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
        extraSecrets:
          airflow-ssh-secret:
            data: |
              gitSshKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDemVUMVVLVkVCVFJkU2pUK1M2ekpyc05hc3J6L3pMVm1TVUFIR3d0S2Y2QUFBQUpnckNNMVFLd2pOClVBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ3plVDFVS1ZFQlRSZFNqVCtTNnpKcnNOYXNyei96TFZtU1VBSEd3dEtmNkEKQUFBRUFFQUlaS0pwM0ZZUVd3TVRBVzRCVFg4S2N1bVVoNVJVak5SWEp4TGRFcTdiTjVQVlFwVVFGTkYxS05QNUxyTW11dwoxcXl2UC9NdFdaSlFBY2JDMHAvb0FBQUFFV2RsY25OdmJuSnpRR3hwZG1VdVkyOXRBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
          airflow-metadata-secret:
            data: |
              connection: cG9zdGdyZXNxbDovL3NkczhmMjNjNzpmY2EzMTY5MWQyYzhlZThlYzAwZmZkMjVmNGRjN2U0ZUBwb3N0Z3Jlcy1wb3N0Z3Jlc3FsLmRhdGFiYXNlLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvYWlyZmxvdw==
          my-webserver-secret:
            data: |
              webserver-secret-key: NzA3YTNiOTE4MzdhYTNjOTQ0N2U5ZTdmMDUyZTZmNGE=
        
    chart: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
