apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: mysql
  # deployed yaml
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.4.1
    helm:
      values: |-
        auth:
          database: "owshq"
          username: "gerson"
          password: "8a3d105a0be11de967ee825a671998e1"
        image:
          debug: true
        primary:
          startupProbe:
            enabled: false
          livenessProbe:
            enabled: false
          readinessProbe:
            enabled: false
          persistence:
            size: 10Gi
          service:
            type: LoadBalancer
        secondary:
          persistence:
            size: 10Gi
          service:
            type: LoadBalancer
    chart: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
