apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: ingestion-from-local-data-file-to-bronze-tables
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "gersonrs/spark:0.1"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///app/ingestion_to_bronze.py"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    fs.s3a.endpoint: "http://10.108.233.87:9000"
    fs.s3a.access.key: "gerson"
    fs.s3a.secret.key: "rHasMuUFzGY0REI2H6RcdaJFNZp9b9ht"
    fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    fs.s3a.path.style.access: "True"
  sparkConf:
    spark.delta.logStore.class: "org.apache.spark.sql.delta.storage.S3SingleDriverLogStore"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: default
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 3.0.0