apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: ingestion-to-bronze
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "gersonrs/spark:0.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/ingestion_to_bronze.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    "fs.s3a.endpoint": "minio.deepstorage.svc.cluster.local:9000"
    "fs.s3a.access.key": "gerson"
    "fs.s3a.secret.key": "rHasMuUFzGY0REI2H6RcdaJFNZp9b9ht"
    "fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "fs.s3a.path.style.access": "True"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: default
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 3.1.1