apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: database
type: Opaque
data:
  password: "ZmNhMzE2OTFkMmM4ZWU4ZWMwMGZmZDI1ZjRkYzdlNGU="
  postgres-password: "YzA5NzI0ZmYwYjNhN2RlODZiNzMxODU3NTBhMDY2NWI="
  replicationPasswordKey: "MWM1OWI1NDY5ZDg1NWI5M2EwY2VmYjVjOGY5NTIzNGI="